### ISSUE TITLE
Error Handling Best Practices

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/wormhole-sdk#70]
This Issue continues the discussion of error handling best practices, and builds
on top of [this Issue for the rest.bitcoin.com repo](https://github.com/Bitcoin-com/rest.bitcoin.com/issues/29). This issue focuses on
the client-side libraries such as [BITBOX](https://github.com/Bitcoin-com/bitbox-javascript-sdk) and [Wormhole](https://github.com/Bitcoin-com/wormhole-sdk).

Again, I'll focus on the Wormhole `dataRetrieval/info` endpoint as an example,
and use the common `ECONNRESET` error as an example.

Here is the current code in [wormhole-sdk/src/DataRetrieval.js](https://github.com/Bitcoin-com/wormhole-sdk/blob/38d91d9fd654ba993e225fc596306326550515fc/src/DataRetrieval.js#L84).

```javascript
async info() {
  try {
    const response = await axios.get(`${this.restURL}dataRetrieval/info`)
    return response.data
  } catch (error) {
    throw error.response.data
  }
}
```

After implementing the suggested error handling improvements in rest.bitcoin.com,
the above code returns this error message:

```
TypeError: Cannot read property 'data' of undefined
    at DataRetrieval.info (/home/trout/work/bch/wormhole-sdk/lib/DataRetrieval.js:101:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Which is completely unhelpful. And the above message is caused by the `catch`
handler experiencing an unhandled error because `error.response.data` does not
exist.

Changing to this:

```javascript
async info() {
  try {
    const response = await axios.get(`${this.restURL}dataRetrieval/info`)
    return response.data
  } catch (error) {
    if (error.response && error.response.data) throw error.response.data
    throw error
  }
}
```

will results in this error message instead:

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:322:15)
    at Socket.socketOnEnd (_http_client.js:425:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.17.1' },
     method: 'get',
     url: 'http://localhost:3000/v1/dataRetrieval/info',
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: true,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        hostname: 'localhost',
        port: '3000',
        path: '/v1/dataRetrieval/info',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        nativeProtocols: [Object],
        pathname: '/v1/dataRetrieval/info' },
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'GET /v1/dataRetrieval/info HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.17.1\r\nHost: localhost:3000\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/v1/dataRetrieval/info',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://localhost:3000/v1/dataRetrieval/info' },
  response: undefined }
```

While this output is verbose and ugly, it's also full of data that the end users
application can interrogate to understand *what happened* and *how to handle it*.

**Comment by cgcardona** [comment]
Wonderful! This is done https://github.com/Bitcoin-com/wormhole-sdk/commit/d0a6ffdaa8f2c2a4764755f3dc1b72b15e758f77

Live in v1.2.3 https://github.com/Bitcoin-com/wormhole-sdk/releases/tag/1.2.3
